spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433,127.0.0.2:5433,127.0.0.3:5433/inventory
    username: yugabyte
    hikari:
      transaction-isolation: 4 # default: Repeatable Read / SNAPSHOT
  jpa:
    open-in-view: false
    show-sql: false # prefer the org.hibernate.SQL below
    properties:
      hibernate.format_sql: false

logging.level:
  java.sql: DEBUG
  com.zaxxer.hikari.HikariConfig: DEBUG
  org.springframework.retry: TRACE
  #org.postgresql: DEBUG
  #org.hibernate.SQL: DEBUG
  #org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  #org.springframework.jdbc.core.JdbcTemplate: DEBUG
  #org.springframework.jdbc.core.StatementCreatorUtils: TRACE
  #com.zaxxer.hikari: TRACE